language: python
dist: xenial
cache: pip
python:
  - 3.6
  - 3.7
stages:
  - test
  - deploy
before_script:
  - pip install -U poetry tox-travis codecov
script:
  - tox
jobs:
  include:
    - stage: deploy
      python: 3.7
      script: skip
      before_install:
        - pip install 'poetry==1.1.7'
      install:
        - poetry install
      before_deploy:
        - poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true
      after_success:
        - codecov
